djangoWeather/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from weather import api
from .yasg import urlpatterns as doc_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls', namespace='weather')),
    path('user/', include('users.urls', namespace='user')),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/mostsearchedcity/', api.FrequentlySearchedAPIView.as_view()),
    path('api/notoftensearchedcity/', api.NotFrequentlySearchedAPIView.as_view()),
    path('api/getstatistic/<str:city>/', api.GetStatisticAPIView.as_view()),
    path('api/weatherdata/<str:city>/', api.WeatherDataAPIView.as_view()),
    path('api/moreweatherdata/<str:city>/', api.DetailWeatherDataAPIView.as_view()),
] + doc_url

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from djangoWeather import settings
from users import views, payments

app_name = 'user'

urlpatterns = [
    path('login/', views.SignInView.as_view(), name='sign-in'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL} ,name='logout'),
    path('registration/', views.SignUpView.as_view(), name='sign-up'),
    path('buy/', payments.PaymentView.as_view(), name='payment'),
    path('confirmation/', views.ConfirmationView.as_view(), name='confirmation'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/settings/', views.ProfileSettingsView.as_view(), name='settings'),
]

weather/urls.py
from django.urls import path

from . import views

app_name: str = 'weather'

urlpatterns = [
    path('', views.RedirectToView.as_view(), name='redirect'),
    path('weatherfinder/', views.WeatherPageView.as_view(), name='first_page'),
    path('weatherfinder/ratings/', views.RatingView.as_view(), name='ratings'),
    path('weatherfinder/<str:city>/', views.WeatherPageView.as_view(), name='page_for_find_city_by_name'),
]

templates/includes/footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="https://vk.com/intensy"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

templates/includes/header.html
{% load static %}

<div class="container">
  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{% url 'weather:first_page' %}" class="nav-link px-3 link-secondary">Главная</a></li>
      <li><a href="{% url 'weather:ratings' %}" class="nav-link px-3 link-body-emphasis">Топ-лист поисков</a></li>
    </ul>
    {% if form %}
    	<form class="d-flex" action="{% url 'weather:first_page' %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-outline-success me-2" type="submit">Поиск</button>
      {{ form.name }}
    </form>
    {% endif %}
    <ul class="nav col-12 col-lg-auto justify-content-center mb-md-0">
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'user:profile' request.user.pk %}" class="nav-link px-3 link-secondary">{{ request.user.username }}</a></li>
        <li><a href="{% url 'user:logout' %}" class="btn btn-outline-secondary">Выйти</a></li>
      {% else %}
        <li><a href="{% url 'user:sign-in' %}" class="btn btn-outline-info me-2">Войти</a></li>
        <li><a href="{% url 'user:sign-up' %}"  class="btn btn-warning">Регистрация</a></li>
      {% endif %}
    </ul>
  </div>
</div>

templates/includes/icons.html
{% load static %}

{% if 'ясно' in weather_status.split %}
  <link rel="icon" href="{% static 'img/sun.png' %}">
{% elif 'облачно' in weather_status.split %}
  <link rel="icon" href="{% static 'img/sun-cloud.png' %}">
{% elif 'дожд' in weather_status.split %}
  <link rel="icon" href="{% static 'img/rain-cloud.png' %}">
{% elif 'сне' in weather_status.split or 'снеж' in weather_status.split  %}
  <link rel="icon" href="{% static 'img/snow.png' %}">
{% endif %}