djangoWeather/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from weather import api
from .yasg import urlpatterns as doc_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls', namespace='weather')),
    path('user/', include('users.urls', namespace='user')),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.authtoken')),
    path('api/mostsearchedcity/', api.FrequentlySearchedAPIView.as_view()),
    path('api/notoftensearchedcity/', api.NotFrequentlySearchedAPIView.as_view()),
    path('api/getstatistic/<str:city>/', api.GetStatisticAPIView.as_view()),
    path('api/weatherdata/<str:city>/', api.WeatherDataAPIView.as_view()),
    path('api/moreweatherdata/<str:city>/', api.DetailWeatherDataAPIView.as_view()),
] + doc_url

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from djangoWeather import settings
from users import views, payments

app_name = 'user'

urlpatterns = [
    path('login/', views.SignInView.as_view(), name='sign-in'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL} ,name='logout'),
    path('registration/', views.SignUpView.as_view(), name='sign-up'),
    path('buy/', payments.PaymentView.as_view(), name='payment'),
    path('confirmation/', views.ConfirmationView.as_view(), name='confirmation'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/settings/', views.ProfileSettingsView.as_view(), name='settings'),
]

users/models.py
import datetime as dt
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.http import Http404
from django.shortcuts import get_object_or_404
from rest_framework.authtoken.models import Token


class User(AbstractUser):
    USER_PERMISSIONS: tuple[tuple[str]] = (
        ('Default', 'Default'),
        ('Premium', 'Premium'),
    )
    user_status = models.CharField(
        max_length=10,
        verbose_name='Статус',
        choices=USER_PERMISSIONS,
        default='Default',
        blank=True
    )

    class Meta:
        verbose_name: str = 'Пользователь'
        verbose_name_plural: str = 'Пользователи'


class Subscription(models.Model):
    client = models.ForeignKey(
        verbose_name='Покупатель',
        to='User',
        on_delete=models.PROTECT,
        related_name='subscription'
    )
    order = models.ForeignKey(
        verbose_name='Платёж',
        to='PaymentModel',
        on_delete=models.SET_NULL,
        null=True,
        related_name='subscription'
    )
    start_date = models.DateField(
        verbose_name='Дата старта подписки',
        blank=True
    )
    end_date = models.DateField(
        verbose_name='Дата окончания подписки',
        blank=True
    )

    class Meta:
        verbose_name: str = 'Подписка'
        verbose_name_plural: str = 'Подписки'

    def __str__(self) -> str:
        return f'Подписка {self.id}'


class PaymentModel(models.Model):
    user = models.ForeignKey(
        verbose_name='Пользователь',
        to='User',
        on_delete=models.SET_NULL,
        null=True,
        related_name='payment'
    )
    uuid = models.UUIDField(
        verbose_name='Уникальный код'
    )
    is_accepted = models.BooleanField(
        verbose_name='Статус платежа',
        default=False,
        blank=True
    )
    date = models.DateField(
        verbose_name='Дата создания',
        auto_now_add=True
    )

    class Meta:
        verbose_name: str = 'Платёж'
        verbose_name_plural: str = 'Платёжи'

    def __str__(self) -> str:
        return f'{self.uuid}'


@receiver(post_save, sender=User)
def user_token_handler(instance: User, **kwargs):
    if not Token.objects.filter(user=instance):
        Token(key=uuid.uuid4(), user=instance).save()


@receiver(pre_save, sender=Subscription)
def subscription_handler(instance: Subscription, **kwargs):
    try:
        sub = get_object_or_404(
            Subscription.objects.order_by('end_date'),
            client=instance.client
        )
    except Http404:
        return

    date_checker = sub.end_date if sub.end_date >= dt.date.today() else dt.date.today()

    instance.start_date = date_checker
    instance.end_date = date_checker + dt.timedelta(days=30)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'text',
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'Your username'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control',
            'id': 'floatingPassword',
            'placeholder': 'Password'
        }
    ))

    class Meta:
        model: User = User
        fields: tuple[str] = ('username', 'password')


class RegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'text',
            'class': 'form-control mb-1',
            'id': 'floatingInput',
            'placeholder': 'Your username'
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control mb-1',
            'id': 'floatingPassword1',
            'placeholder': 'Password'
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control mb-1',
            'id': 'floatingPassword2',
            'placeholder': 'Repeat password'
        }
    ))

    class Meta:
        model: User = User
        fields: tuple[str] = ('username', 'password1', 'password2')


class ProfileSettingsForm(forms.ModelForm):
    old_password = forms.CharField(
        label='Старый пароль',
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control mb-1',
                'id': 'floatingPassword1',
                'placeholder': 'Введите ваш старый пароль'
            }
        )
    )
    new_password1 = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control mb-1',
                'id': 'floatingPassword2',
                'placeholder': 'Введите ваш новый пароль'
            }
        )
    )
    new_password2 = forms.CharField(
        label='Повтор нового пароля',
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control mb-1',
                'id': 'floatingPassword3',
                'placeholder': 'Введите ваш новый пароль'
            }
        )
    )

    class Meta:
        model = User
        fields: tuple[str] = ('old_password','new_password1','new_password2')

users/views.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Max
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page
from rest_framework.authtoken.models import Token

from users import forms
from users.forms import ProfileSettingsForm
from users.mixins import IsAuthenticatedMixin, RedirectToProfileMixin
from users.models import User
from weather.forms import FindCityForm


class SignInView(IsAuthenticatedMixin, LoginView):
    """
    Данный класс позволяет авторизоваться пользователям.
    """
    form_class = forms.LoginForm
    template_name: str = 'users/login.html'

    def get_success_url(self):
        return reverse('weather:first_page')


class SignUpView(IsAuthenticatedMixin, generic.CreateView):
    """
    Данный класс позволяет зарегистрироваться пользователям.
    """
    form_class = forms.RegistrationForm
    template_name = 'users/registration.html'

    def get_success_url(self):
        return reverse('weather:first_page')


@method_decorator(cache_page(60*5), name='dispatch')
class ProfileView(LoginRequiredMixin, RedirectToProfileMixin, generic.FormView):
    """
    Данный класс отображает страницу профиля пользователя исключительно для своего аккаунта.
    """
    form_class = FindCityForm
    template_name: str = 'users/profile.html'
    login_url = reverse_lazy('user:sign-in')

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context: dict[str, Any] = super().get_context_data()
        context['end_date'] = self.request.user.subscription.aggregate(Max('end_date'))['end_date__max']
        context['token'] = Token.objects.get(user=self.request.user).key
        return context


class ProfileSettingsView(LoginRequiredMixin, RedirectToProfileMixin, generic.TemplateView):
    """
    Данный класс отображает страницу с настройками (возможность смены пароля)
    исключительно для своего аккаунта.
    """
    template_name = 'users/settings.html'

    def get_context_data(self, *args, **kwargs):
        context: dict[str, Any] = super().get_context_data()
        context['form'] = FindCityForm
        context['settings_form'] = ProfileSettingsForm
        return context

    def get_success_url(self):
        return self.follow_to('profile')

    def post(self, *args, **kwargs):
        form = ProfileSettingsForm(self.request.POST)
        user = User.objects.get(username=self.request.user.username)
        if form.is_valid():
            if user.check_password(form.data['old_password']):
                user.set_password(form.data['new_password1'])
                user.save()
            return self.follow_to('profile')
        return self.follow_to('settings')


class ConfirmationView(generic.TemplateView):
    """
    Данный класс отображает статус платежа на странице.
    """
    def get(self, request, *args, **kwargs):
        return render(self.request, 'payment/confirmation.html')

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<main class="form-signin w-25 m-auto">
  <form method="post">
    {% csrf_token %}
    <h1 class="h4 mb-3 fw-normal">Пожалуйста, войдите в свой аккаунт:</h1>

    <div class="form-floating">
      {{ form.username }}
      <label for="floatingInput">Имя пользователя</label>
    </div>
    <div class="form-floating">
      {{ form.password }}
      <label for="floatingPassword">Пароль</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Запомнить меня
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Войти</button>
    <p class="mt-5 mb-3 text-body-secondary">© 2017–2023</p>
  </form>
</main>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalTour">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-body p-5">
        <ul class="d-grid my-3 list-unstyled small">
          <li class="mx-auto justify-content-center">
            <div>
              <img src="{% static 'img/avatar1.png' %}" alt="#" style="object-fit: contain" width="150px" height="150px">
            </div>
          </li>
          <li class="mx-auto justify-content-center mb-4">
            <svg class="bi text-body-secondary flex-shrink-0" width="48" height="48"><use xlink:href="#grid-fill"></use></svg>
            <div>
              <h5 class="mb-0">Профиль: {{ user.username }}</h5>
            </div>
          </li>
          <li class="d-flex gap-4 mb-2">
            <svg class="bi text-body-secondary flex-shrink-0" width="48" height="48"><use xlink:href="#grid-fill"></use></svg>
            <div>
              <h5 class="mb-0">Статус аккаунта</h5>
              {{ user.user_status.capitalize }}
            </div>
          </li>
          <li class="d-flex gap-4 mb-2">
            <svg class="bi text-body-secondary flex-shrink-0" width="48" height="48"><use xlink:href="#grid-fill"></use></svg>
            <div>
              <h5 class="mb-0">Дата окончания подписки</h5>
              {{ end_date }}
            </div>
          </li>
          <li class="d-flex gap-4">
            <svg class="bi text-warning flex-shrink-0" width="48" height="48"><use xlink:href="#bookmark-star"></use></svg>
            <div>
              <details>
                <summary class="mb-0">Ваш персональный токен для входа</summary>
                <div>{{ token }}</div>
              </details>
            </div>
          </li>
        </ul>
        <a href="{% url 'user:settings' request.user.pk %}" type="button" class="btn btn-lg btn-primary  w-100" data-bs-dismiss="modal">
          Настройки
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/users/registration.html
{% extends 'base.html' %}

{% block content %}
  <main class="form-signin w-25 m-auto">
  <form method="post">
    {% csrf_token %}
    <h1 class="h4 mb-3 fw-normal">Please sign up!</h1>

    <div class="form-floating">
      {{ form.username }}
      <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating">
      {{ form.password1 }}
      <label for="floatingPassword1">Password</label>
    </div>
    <div class="form-floating">
      {{ form.password2 }}
      <label for="floatingPassword2">Password</label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Sign Up!</button>
    <p class="mt-5 mb-3 text-body-secondary">© 2017–2023</p>
  </form>
</main>
{% endblock %}

templates/users/settings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalTour">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-body p-5">
          <form action="{% url 'user:settings' request.user.pk %}" method="post">
            {% csrf_token %}
            {{ settings_form.as_p }}
            <button type="submit" class="btn btn-lg btn-primary  w-100" data-bs-dismiss="modal">Сохранить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}